### ISSUE TITLE
No Results displayed in SKY Monitoring table

### ISSUE THREAD

**Issue by bbarneveld** [SoftwareAG/webmethods-integrationserver-skyprofiler#3]
I've followed the description and everything seems up-and-running, but when I start a service I don't get any results!
![centos - netstat](https://user-images.githubusercontent.com/27193612/27632983-b948665a-5bfd-11e7-85b7-c94e4cae5d49.PNG)
![kafka](https://user-images.githubusercontent.com/27193612/27632978-b9439878-5bfd-11e7-82e5-629bb82be710.PNG)
![mongodb](https://user-images.githubusercontent.com/27193612/27632979-b9466bfc-5bfd-11e7-9b1a-0f4b87963dac.PNG)
![sky - configuration](https://user-images.githubusercontent.com/27193612/27632981-b9472830-5bfd-11e7-8801-22a5ef775afe.PNG)
![sky - integration server connection](https://user-images.githubusercontent.com/27193612/27632982-b947e748-5bfd-11e7-8494-0464271b3d60.PNG)
![sky-profiler](https://user-images.githubusercontent.com/27193612/27632980-b9473cbc-5bfd-11e7-9481-124511156e7c.PNG)
![zookeeper](https://user-images.githubusercontent.com/27193612/27632984-b956b462-5bfd-11e7-928f-ba03faa4e067.PNG)

Note: I'm working on my Windows Laptop connecting to local VirtualBox with Centos 7 Linux running webM 10.0 fully patched.

I have no physical connection to any network, use WiFi for Internet Access

**Comment by bbarneveld** [comment]
192.168.56.101 is the IP of "mcberba03"

**Comment by bbarneveld** [comment]
Latest observation: If I just start all engines, after about a minute I get the following stackdump from skyprofiler server:

2017-06-28 15:23:05.496  INFO 8396 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-06-28 15:23:05.507  INFO 8396 --- [           main] c.s.skyprofiler.SkyProfilerApplication   : Started SkyProfilerApplication in 19.533 seconds (JVM running for 20.351)
**2017-06-28 15:23:05.817  INFO 8396** --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
**2017-06-28 15:24:18.120  INFO 8396** --- [MessageBroker-1] o.apache.coyote.http11.Http11Processor   : An error occurred in processing while on a non-container thread. The connection
will be closed immediately

java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_131]
        at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_131]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_131]
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1221) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:451) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:441) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11OutputBuffer.flushBuffer(Http11OutputBuffer.java:514) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:243) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1495) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:284) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.Response.action(Response.java:167) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:336) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:303) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.Response.flushBuffer(Response.java:541) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:158) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]

        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:158) [spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]

        at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:96) [spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:350) [spring-websocket-4.3.4.RELEASE.
jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:322) [spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELE
ASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendHeartbeat(AbstractSockJsSession.java:255) [spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.R
ELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession$HeartbeatTask.run(AbstractSockJsSession.java:451) [spring-websocket-4.3.4.RELEASE.jar!/:4.3
.4.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]

2017-06-28 15:24:18.161 ERROR 8396 --- [MessageBroker-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to write SockJsFrame content='h'; nested exception is org.apache.catalina.connector.ClientAbortExcepti
on: java.io.IOException: An established connection was aborted by the software in your host machine
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:339) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.REL
EASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendHeartbeat(AbstractSockJsSession.java:255) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.
RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession$HeartbeatTask.run(AbstractSockJsSession.java:451) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.
3.4.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]
Caused by: org.apache.catalina.connector.ClientAbortException: java.io.IOException: An established connection was aborted by the software in your host machine
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:340) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:303) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.Response.flushBuffer(Response.java:541) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:158) ~[spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE
]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:158) ~[spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE
]
        at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:96) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:350) ~[spring-websocket-4.3.4.RELEASE
.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:322) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.REL
EASE]
        ... 10 common frames omitted
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
        at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_131]
        at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_131]
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_131]
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1221) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:451) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:441) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11OutputBuffer.flushBuffer(Http11OutputBuffer.java:514) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:243) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1495) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:284) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.Response.action(Response.java:167) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:336) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        ... 21 common frames omitted

**Comment by bbarneveld** [comment]
The thrown error occurs sporadicly: not reproducable!?

**Comment by bbarneveld** [comment]
![sky - server jmc kafka mbeans](https://user-images.githubusercontent.com/27193612/27676464-49700c00-5cae-11e7-809e-144e8e705372.png)
![sky - server jmc kafka thread](https://user-images.githubusercontent.com/27193612/27676466-49716a6e-5cae-11e7-9a81-274795144030.png)
![sky - server netstat](https://user-images.githubusercontent.com/27193612/27676465-497151b4-5cae-11e7-8b37-c877a8c8661d.png)

**Comment by bbarneveld** [comment]
I realy execute the service:

![is service usage](https://user-images.githubusercontent.com/27193612/27676895-075e7af2-5cb0-11e7-9d06-ac9546da0ab9.png)

**Comment by bbarneveld** [comment]
![designer - service](https://user-images.githubusercontent.com/27193612/27678008-e7f3cbaa-5cb3-11e7-9530-d48b2bc94fff.PNG)

**Comment by bbarneveld** [comment]
![is - package config](https://user-images.githubusercontent.com/27193612/27678829-ec3ba3c4-5cb6-11e7-8d11-ce29216ea826.PNG)

**Comment by bbarneveld** [comment]
FQDN - Fully Qualified DNS Name in "/etc/hosts" on VirtualBox VM did the job!
