### ISSUE TITLE
Failed to write SockJsFrame content='h'; nested exception is org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by tanacute** [SoftwareAG/webmethods-integrationserver-skyprofiler#4]
Hi,

I had followed the tutorial exactly and installed all the necessary software. However I am getting this error while clicking 'Start' from SKY Profiler webpage - http://localhost:8080

2017-07-28 23:07:58.115 ERROR 4476 --- [MessageBroker-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
 
org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to write SockJsFrame content='h'; nested exception is org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:339) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendHeartbeat(AbstractSockJsSession.java:255) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession$HeartbeatTask.run(AbstractSockJsSession.java:451) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:340) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:303) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.Response.flushBuffer(Response.java:541) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:158) ~[spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:158) ~[spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]
        at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:96) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:350) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:322) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        ... 10 common frames omitted
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_131]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_131]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_131]
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1221) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:451) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:441) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11OutputBuffer.flushBuffer(Http11OutputBuffer.java:514) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:243) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1495) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:284) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.Response.action(Response.java:167) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:336) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        ... 21 common frames omitted

Connectivity between zookeeper is fine. Created a topic 'default' and configured in Skyprofiler UI. Publish-Subscribe works fine (Tested by using Kafka shell tool).
Tried rebuilding skyprofilier jar file and package but no luck. I am using Linux Redhat 7.2

**Comment by YashwanthKumarJ** [comment]
Hi Tanacute,

The above stack trace is from server side. And looks like connection between browser and server failed during websocket connection. However, we have retry mechanism at the UI side to connect back to the server. Is this happening continuously or once in a while?

BTW, which browser are you using?

**Comment by tanacute** [comment]
Hi Yashwant,

Yes, this stack trace is from skyprofiler server and I can also see small popup notification in UI for websocket connection failure. I tried in Chrome version 60 and Mozilla Firefox.

However in both connection, same error

Thanks,
Tanveer

**Comment by YashwanthKumarJ** [comment]
Is that pop-up coming all the time? Did u observe that pop-up only after clicking on Start button or soon after accessing the page?

Just restart the server once and access the page in a new tab or window.

**Comment by tanacute** [comment]
yes, pop-up after clicking the start button , tried starting servers and opening in different tab but still getting error: 

Now, I notice a different error, here is stack trace.

failed; nested exception is org.springframework.web.socket.sockjs.SockJsException: Uncaught failure in SockJS request, uri=http://localhost:8080/skyprofiler-websocket/825/mwn2lw5m/xhr_streaming?t=1501520292940; nested exception is org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to open session; nested exception is org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to write SockJsFrame content='o'; nested exception is org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe] with root cause

java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[na:1.8.0_131]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[na:1.8.0_131]
        at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[na:1.8.0_131]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[na:1.8.0_131]
        at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1221) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketWrapperBase.flushBlocking(SocketWrapperBase.java:451) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.tomcat.util.net.SocketWrapperBase.flush(SocketWrapperBase.java:441) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11OutputBuffer.flushBuffer(Http11OutputBuffer.java:514) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11OutputBuffer.flush(Http11OutputBuffer.java:243) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.http11.Http11Processor.flush(Http11Processor.java:1495) [tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:284) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.coyote.Response.action(Response.java:167) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:336) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:303) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.Response.flushBuffer(Response.java:541) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:158) ~[spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176) ~[tomcat-embed-core-8.5.6.jar!/:8.5.6]
        at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:158) ~[spring-security-web-4.1.3.RELEASE.jar!/:4.1.3.RELEASE]
        at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:96) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:350) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:322) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.StreamingSockJsSession.handleRequestInternal(StreamingSockJsSession.java:75) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.handleInitialRequest(AbstractHttpSockJsSession.java:215) ~[spring-websocket-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.so

**Comment by YashwanthKumarJ** [comment]
Post offline discussion on this issue, couple of changes / verification points were discussed. Yet to receive an update on how far we reached by trying out the changes discussed.
