### ISSUE TITLE
No data capture in Sky Profiler

### ISSUE THREAD

**Issue by ooijw** [SoftwareAG/webmethods-integrationserver-skyprofiler#8]
Is Sky Profiler support for IS v9.9?

Also, the below error has been thrown when i clicked on the "Take Baseline" service.

2017-12-14 11:21:42.562 ERROR 10312 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.Exception: ISHost not found in the cache to take baseline.] with root cause

        at com.softwareag.skyprofiler.controller.TreeDataController.takeBaseline(TreeDataController.java:90) ~[classes!/:1.0-RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[spring-webmvc-4.3.4.RELEASE.jar!/:4.3.4.RELEASE]

**Comment by YashwanthKumarJ** [comment]
It does. 
what is the status of this issue?
